### ISSUE TITLE
unicode problem with py2.7

### ISSUE THREAD

**Issue by rhoerbe** [schlatterbeck/snxvpn#3]
One-time Password: 
Traceback (most recent call last):
  File "/usr/bin/snxconnect", line 5, in <module>
    main ()
  File "/usr/lib/python2.7/site-packages/snxconnect.py", line 459, in main
    result = rq.login ()
  File "/usr/lib/python2.7/site-packages/snxconnect.py", line 198, in login
    self.generate_snx_info ()
  File "/usr/lib/python2.7/site-packages/snxconnect.py", line 137, in generate_snx_info
    , 1 # ???
TypeError: Struct() argument 1 must be string, not unicode

workaround: start with py3

**Comment by schlatterbeck** [comment]
Fixed, seems earlier python2.7 versions want the format argument to struct.pack to be string not unicode. Fortunately python3 also accepts a byte-string here.
