### ISSUE TITLE
SSL problem with Python 3.5

### ISSUE THREAD

**Issue by mkurz** [schlatterbeck/snxvpn#6]
Installed via `pip3`. With python 2.7 no problem occurs.
```
$ snxconnect -H <ipaddress> -U <user>
sslvpn/Login/Login
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mkurz/.local/bin/snxconnect", line 5, in <module>
    main ()
  File "/home/mkurz/.local/lib/python3.5/site-packages/snxconnect.py", line 511, in main
    result = rq.login ()
  File "/home/mkurz/.local/lib/python3.5/site-packages/snxconnect.py", line 168, in login
    self.open ()
  File "/home/mkurz/.local/lib/python3.5/site-packages/snxconnect.py", line 246, in open
    self.f = f = self.opener.open (rq, timeout = 10)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)>
```

**Comment by schlatterbeck** [comment]
This is caused by your VPN provider not having a certificate with a known issuer. Certificate-Checking in python3 (and later versions of python2.7) has improved, I'll try to come up with an override option and a howto how to get the certificate downloaded and provided to the program... Hard to test, though because this error doesn't occur for me...

**Comment by mkurz** [comment]
I solved this by adding the certificate to the known ca certificates (using Ubuntu):
```
$ sudo cp certificate.crt /usr/local/share/ca-certificates/
$ sudo update-ca-certificates
```
